options(stringsAsFactors=FALSE,warn=1)
suppressPackageStartupMessages({library(dplyr);library(tidyr)})
set.seed(20260815)
project<-normalizePath(getwd(),winslash="/",mustWork=TRUE);if(basename(project)!="longitudinal_upgrade")stop("Run from project root")
root<-file.path(project,"causal_landmark");dd<-file.path(project,"data","causal_landmark");od<-file.path(project,"results","causal_landmark");td<-file.path(project,"tables","causal_landmark");fd<-file.path(project,"figures","causal_landmark");ld<-file.path(project,"logs","causal_landmark");for(z in c(root,file.path(root,"scripts"),dd,od,td,fd,ld))dir.create(z,FALSE,TRUE)
logcon<-file(file.path(ld,"00_landmark_data_audit.log"),"wt",encoding="UTF-8");sink(logcon,split=TRUE);sink(logcon,type="message");on.exit({sink(type="message");sink();close(logcon)},add=TRUE)
d0<-readRDS(file.path(project,"data","causal","causal_long_full_internal_restricted.rds"))
# Outcome values are deliberately excluded before the treatment-weighting gate.
d<-d0%>%select(-any_of(c("HD_z","KDM_BAA")))
wide<-d%>%filter(wave%in%c(2004,2006))%>%select(Idind,wave,fuel_state)%>%pivot_wider(names_from=wave,values_from=fuel_state,names_prefix="fuel")
initial<-n_distinct(d$Idind);valid04<-sum(!is.na(wide$fuel2004));as04<-sum(wide$fuel2004%in%c("solid_only","mixed"),na.rm=TRUE);valid06<-sum(wide$fuel2004%in%c("solid_only","mixed")&!is.na(wide$fuel2006),na.rm=TRUE)
eligible<-wide%>%filter(fuel2004%in%c("solid_only","mixed"),!is.na(fuel2006))%>%mutate(A=as.integer(fuel2006=="clean_only"),treatment=ifelse(A==1,"clean_only_2006","continued_any_solid_2006"))
sel<-d%>%filter(wave==2009)%>%select(Idind,biomarker2009)%>%distinct()
eligible<-eligible%>%left_join(sel,by="Idind")
flow<-data.frame(stage=c("initial participants","valid 2004 fuel state","any-solid in 2004","valid 2006 treatment","clean-only in 2006","any-solid in 2006","2009 biomarker observed","2009 biomarker missing"),N=c(initial,valid04,as04,valid06,sum(eligible$A==1),sum(eligible$A==0),sum(eligible$biomarker2009==1,na.rm=TRUE),sum(is.na(eligible$biomarker2009)|eligible$biomarker2009!=1)))
write.csv(flow,file.path(td,"Table_landmark_eligibility.csv"),row.names=FALSE)
trial<-data.frame(element=c("Eligibility","Treatment","Assignment","Time zero","Follow-up end","Outcomes","Primary estimand","Analysis"),specification=c("Observed valid any-solid fuel state in 2004 and valid fuel state in 2006; biomarker availability is not an eligibility criterion","A=1 clean-only in 2006; A=0 solid-only or mixed in 2006; no requirement on 2009 fuel","Observational emulation using binary point-treatment overlap weights","2006 fuel decision among the 2004 any-solid landmark cohort","2009 biomarker examination","Primary HD_z; secondary KDM_BAA","E_OW[Y(clean-only 2006)-Y(any-solid 2006)] in the 2004 any-solid overlap population","GLM overlap weighting; CBPS overlap sensitivity; biomarker IPCW and community-robust marginal model only after gate"))
write.csv(trial,file.path(td,"Table_landmark_target_trial.csv"),row.names=FALSE)
saveRDS(eligible,file.path(dd,"landmark_eligible_ids_internal_restricted.rds"),compress="gzip");saveRDS(d%>%filter(Idind%in%eligible$Idind,wave<=2009),file.path(dd,"landmark_long_no_outcomes_internal_restricted.rds"),compress="gzip")
cat("ELIGIBLE=",nrow(eligible)," CLEAN=",sum(eligible$A==1)," ANY_SOLID=",sum(eligible$A==0),"\n",sep="");cat("LANDMARK_DATA_AUDIT=PASS_NO_OUTCOMES_READ\n")

