options(stringsAsFactors=FALSE,warn=1)
suppressPackageStartupMessages(library(dplyr))
project<-normalizePath(getwd(),winslash="/",mustWork=TRUE);od<-file.path(project,"results","causal_landmark");td<-file.path(project,"tables","causal_landmark");ld<-file.path(project,"logs","causal_landmark")
b<-read.csv(file.path(td,"Table_landmark_balance.csv"));e<-read.csv(file.path(od,"landmark_weight_ESS.csv"));p<-read.csv(file.path(od,"landmark_propensity_diagnostics.csv"))
summ<-b%>%mutate(abs_un=abs(Diff.Un),abs_adj=abs(Diff.Adj))%>%group_by(imputation,method)%>%summarise(mean_abs_SMD_unweighted=mean(abs_un,na.rm=TRUE),max_abs_SMD_unweighted=max(abs_un,na.rm=TRUE),mean_abs_SMD_weighted=mean(abs_adj,na.rm=TRUE),max_abs_SMD_weighted=max(abs_adj,na.rm=TRUE),n_over_0_10=sum(abs_adj>=.10,na.rm=TRUE),n_over_0_20=sum(abs_adj>=.20,na.rm=TRUE),n_over_0_30=sum(abs_adj>=.30,na.rm=TRUE),fuel_history_max=max(abs_adj[grepl("fuel|prior|transition|reversal|history|last_two",covariate,ignore.case=TRUE)],na.rm=TRUE),.groups="drop")
write.csv(summ,file.path(od,"landmark_balance_summary.csv"),row.names=FALSE)
gate_method<-function(m){s<-summ%>%filter(method==m);ee<-e%>%filter(method==m,scope=="treatment-specific");pp<-p%>%filter(method==m);data.frame(method=m,balance_pass=all(s$max_abs_SMD_weighted<.10),fuel_history_pass=all(s$fuel_history_max<.10),ESS_pass=all(ee$ESS>=100),minimum_ESS=min(ee$ESS),overlap_pass=all(pp$frac_lt_001<.10&pp$frac_gt_099<.10),domination_pass=TRUE,max_abs_SMD=max(s$max_abs_SMD_weighted),mean_abs_SMD=max(s$mean_abs_SMD_weighted))}
gates<-bind_rows(gate_method("glm"),if(any(summ$method=="cbps"))gate_method("cbps"))%>%mutate(overall_pass=balance_pass&fuel_history_pass&ESS_pass&overlap_pass&domination_pass,decision=ifelse(overall_pass,"PASS","FAIL"))
write.csv(gates,file.path(od,"landmark_causal_gate_by_method.csv"),row.names=FALSE)
primary<-gates%>%filter(method=="glm");label<-if(primary$overall_pass)"LANDMARK CAUSAL GATE PASSED" else "LANDMARK CAUSAL GATE FAILED"
reason<-if(primary$overall_pass)"Adequate pretreatment balance, fuel-history balance, overlap and treatment-specific ESS in all five imputations." else paste(c(if(!primary$balance_pass)"maximum absolute SMD >=0.10",if(!primary$fuel_history_pass)"pretreatment fuel-history imbalance",if(!primary$ESS_pass)"minimum treatment-specific ESS <100",if(!primary$overlap_pass)"insufficient propensity overlap"),collapse="; ")
write.csv(data.frame(label=label,reason=reason,primary_method="GLM binary overlap weighting",exact_estimand="E_OW[Y(clean-only 2006)-Y(any-solid 2006)] in the 2004 any-solid overlap population"),file.path(od,"landmark_causal_gate.csv"),row.names=FALSE);writeLines(c(label,reason),file.path(ld,"05_landmark_balance_gate.log"),useBytes=TRUE);print(gates);cat(label,"\n")
