options(stringsAsFactors=FALSE,warn=1)
suppressPackageStartupMessages({library(dplyr);library(cobalt)})
set.seed(20260815)
project<-normalizePath(getwd(),winslash="/",mustWork=TRUE);dd<-file.path(project,"data","causal_landmark");od<-file.path(project,"results","causal_landmark");td<-file.path(project,"tables","causal_landmark");ld<-file.path(project,"logs","causal_landmark")
gate<-read.csv(file.path(od,"landmark_causal_gate.csv"));if(gate$label!="LANDMARK CAUSAL GATE PASSED")stop("Treatment gate did not pass; IPCW prohibited")
ws<-readRDS(file.path(dd,"landmark_overlap_weights_MICE5_internal_restricted.rds"))
formR<-biomarker2009~A+age2004+sex+province+urban_recent+education_recent+income_recent+income_mean+income_change+assets_recent+assets_mean+assets_change+smoking_recent+alcohol_recent+fuel2004+number_prior_fuel_waves+proportion_prior_solid_only+proportion_prior_mixed+ever_clean_before_2006+ever_mixed_before_2006+number_fuel_transitions+duration_weighted_solid_equivalent_history_to_2004+last_two_wave_pattern
formbal<-A~age2004+sex+province+urban_recent+education_recent+income_recent+income_mean+income_change+assets_recent+assets_mean+assets_change+smoking_recent+alcohol_recent+fuel2004+number_prior_fuel_waves+proportion_prior_solid_only+proportion_prior_mixed+ever_clean_before_2006+ever_mixed_before_2006+number_fuel_transitions+number_clean_to_mixed_reversals+number_mixed_to_solid_reversals+duration_weighted_solid_equivalent_history_to_2004+last_two_wave_pattern
outs<-list();diag<-list();balances<-list();ess<-list()
for(j in 1:5){z<-ws[[j]];z$R<-ifelse(!is.na(z$biomarker2009)&z$biomarker2009==1,1L,0L);fn<-glm(R~A,data=z,family=binomial());fd<-glm(formR,data=z,family=binomial(),na.action=na.exclude);pn<-pmax(pmin(predict(fn,newdata=z,type="response"),.995),.005);pd<-pmax(pmin(predict(fd,newdata=z,type="response"),.995),.005);if(anyNA(pd))stop("IPCW denominator covariates remain missing in imputation ",j);z$biomarker_IPCW<-pn/pd;z$final_weight<-z$w_glm*z$biomarker_IPCW
 obs<-z%>%filter(R==1);bt<-cobalt::bal.tab(formbal,data=obs,weights=obs$final_weight,method="weighting",estimand="ATO",un=TRUE,quick=FALSE);b<-as.data.frame(bt$Balance);b$covariate<-rownames(b);rownames(b)<-NULL;b$imputation<-j;balances[[j]]<-b
 diag[[j]]<-data.frame(imputation=j,N=nrow(obs),mean=mean(obs$final_weight),SD=sd(obs$final_weight),minimum=min(obs$final_weight),P1=quantile(obs$final_weight,.01),P5=quantile(obs$final_weight,.05),median=median(obs$final_weight),P95=quantile(obs$final_weight,.95),P99=quantile(obs$final_weight,.99),maximum=max(obs$final_weight),top1_share=sum(sort(obs$final_weight,decreasing=TRUE)[seq_len(max(1,ceiling(.01*nrow(obs))))])/sum(obs$final_weight))
 ess[[j]]<-bind_rows(obs%>%group_by(A)%>%summarise(N=n(),ESS=sum(final_weight)^2/sum(final_weight^2),.groups="drop")%>%mutate(scope="treatment-specific"),obs%>%summarise(N=n(),ESS=sum(final_weight)^2/sum(final_weight^2))%>%mutate(A=NA,scope="overall"))%>%mutate(imputation=j)
 outs[[j]]<-z;cat("IPCW_DONE=",j,"/5\n",sep="")}
saveRDS(outs,file.path(dd,"landmark_final_weights_MICE5_internal_restricted.rds"),compress="gzip")
b<-bind_rows(balances);d<-bind_rows(diag);e<-bind_rows(ess);write.csv(b,file.path(td,"Table_landmark_balance_after_IPCW.csv"),row.names=FALSE);write.csv(d,file.path(od,"landmark_final_weight_diagnostics.csv"),row.names=FALSE);write.csv(e,file.path(od,"landmark_final_weight_ESS.csv"),row.names=FALSE)
bs<-b%>%mutate(abs_adj=abs(Diff.Adj))%>%group_by(imputation)%>%summarise(max_abs_SMD=max(abs_adj,na.rm=TRUE),mean_abs_SMD=mean(abs_adj,na.rm=TRUE),n_over_0_10=sum(abs_adj>=.10,na.rm=TRUE),fuel_history_max=max(abs_adj[grepl("fuel|prior|transition|reversal|history|last_two",covariate,ignore.case=TRUE)],na.rm=TRUE),.groups="drop")
pass<-all(bs$max_abs_SMD<.10)&all(bs$fuel_history_max<.10)&all(e$ESS[e$scope=="treatment-specific"]>=100)&all(d$top1_share<.10)
write.csv(bs,file.path(od,"landmark_final_balance_summary.csv"),row.names=FALSE);write.csv(data.frame(label=ifelse(pass,"LANDMARK FINAL WEIGHT GATE PASSED","LANDMARK FINAL WEIGHT GATE FAILED"),balance_pass=all(bs$max_abs_SMD<.10),fuel_history_pass=all(bs$fuel_history_max<.10),ESS_pass=all(e$ESS[e$scope=="treatment-specific"]>=100),domination_pass=all(d$top1_share<.10),minimum_ESS=min(e$ESS[e$scope=="treatment-specific"]),maximum_SMD=max(bs$max_abs_SMD)),file.path(od,"landmark_final_weight_gate.csv"),row.names=FALSE);cat(ifelse(pass,"LANDMARK FINAL WEIGHT GATE PASSED","LANDMARK FINAL WEIGHT GATE FAILED"),"\n")
