options(stringsAsFactors=FALSE,warn=1)
suppressPackageStartupMessages({library(dplyr);library(survey);library(cobalt)})
set.seed(20260815)
project<-normalizePath(getwd(),winslash="/",mustWork=TRUE);dd<-file.path(project,"data","causal_landmark");od<-file.path(project,"results","causal_landmark");td<-file.path(project,"tables","causal_landmark");ld<-file.path(project,"logs","causal_landmark")
expected<-"f489497f894be7b6a7f41774f8bdb4df";wf<-file.path(dd,"landmark_overlap_weights_MICE5_internal_restricted.rds");actual<-unname(tools::md5sum(wf));if(tolower(actual)!=expected)stop("Frozen treatment-weight object MD5 mismatch; treatment model may have changed")
ws<-readRDS(wf)
calform<-~age2004+sex+province+urban_recent+education_recent+income_recent+income_mean+income_change+assets_recent+assets_mean+assets_change+smoking_recent+alcohol_recent+fuel2004+number_prior_fuel_waves+proportion_prior_solid_only+proportion_prior_mixed+ever_clean_before_2006+ever_mixed_before_2006+number_fuel_transitions+number_clean_to_mixed_reversals+number_mixed_to_solid_reversals+duration_weighted_solid_equivalent_history_to_2004
balform<-A~age2004+sex+province+urban_recent+education_recent+income_recent+income_mean+income_change+assets_recent+assets_mean+assets_change+smoking_recent+alcohol_recent+fuel2004+number_prior_fuel_waves+proportion_prior_solid_only+proportion_prior_mixed+ever_clean_before_2006+ever_mixed_before_2006+number_fuel_transitions+number_clean_to_mixed_reversals+number_mixed_to_solid_reversals+duration_weighted_solid_equivalent_history_to_2004+last_two_wave_pattern
outs<-list();caldiag<-list();balances<-list();ess<-list();wdiag<-list()
for(j in 1:5){z<-ws[[j]];z$R<-ifelse(!is.na(z$biomarker2009)&z$biomarker2009==1,1L,0L);z$calibration_factor<-NA_real_;z$final_calibrated_weight<-NA_real_
 for(a in 0:1){full<-z%>%filter(A==a);obs<-full%>%filter(R==1);Xfull<-model.matrix(calform,data=full);target<-colSums(Xfull*full$w_glm);des<-svydesign(ids=~1,weights=~w_glm,data=obs)
  cd<-calibrate(des,formula=calform,population=target,calfun="raking",bounds=c(.02,50),epsilon=1e-7,maxit=500,force=FALSE);fw<-weights(cd);ii<-match(obs$Idind,z$Idind);z$final_calibrated_weight[ii]<-fw;z$calibration_factor[ii]<-fw/obs$w_glm
  achieved<-colSums(model.matrix(calform,data=obs)*fw);relerr<-max(abs(achieved-target)/pmax(abs(target),1e-8));caldiag[[length(caldiag)+1]]<-data.frame(imputation=j,A=a,N_full=nrow(full),N_observed=nrow(obs),max_relative_total_error=relerr,min_factor=min(fw/obs$w_glm),max_factor=max(fw/obs$w_glm),converged=relerr<1e-6)}
 obs<-z%>%filter(R==1);bt<-bal.tab(balform,data=obs,weights=obs$final_calibrated_weight,method="weighting",estimand="ATO",un=TRUE,quick=FALSE);b<-as.data.frame(bt$Balance);b$covariate<-rownames(b);rownames(b)<-NULL;b$imputation<-j;balances[[j]]<-b
 ess[[j]]<-bind_rows(obs%>%group_by(A)%>%summarise(N=n(),ESS=sum(final_calibrated_weight)^2/sum(final_calibrated_weight^2),.groups="drop")%>%mutate(scope="treatment-specific"),obs%>%summarise(N=n(),ESS=sum(final_calibrated_weight)^2/sum(final_calibrated_weight^2))%>%mutate(A=NA,scope="overall"))%>%mutate(imputation=j)
 w<-obs$final_calibrated_weight;wdiag[[j]]<-data.frame(imputation=j,N=length(w),mean=mean(w),SD=sd(w),minimum=min(w),P1=quantile(w,.01),P5=quantile(w,.05),median=median(w),P95=quantile(w,.95),P99=quantile(w,.99),maximum=max(w),top1_share=sum(sort(w,decreasing=TRUE)[seq_len(ceiling(.01*length(w)))])/sum(w));outs[[j]]<-z;cat("CALIBRATED_IPCW_DONE=",j,"/5\n",sep="")}
saveRDS(outs,file.path(dd,"landmark_calibrated_final_weights_MICE5_internal_restricted.rds"),compress="gzip")
b<-bind_rows(balances);e<-bind_rows(ess);wd<-bind_rows(wdiag);cd<-bind_rows(caldiag);bs<-b%>%mutate(abs_adj=abs(Diff.Adj))%>%group_by(imputation)%>%summarise(max_abs_SMD=max(abs_adj,na.rm=TRUE),mean_abs_SMD=mean(abs_adj,na.rm=TRUE),n_over_0_10=sum(abs_adj>=.10,na.rm=TRUE),fuel_history_max=max(abs_adj[grepl("fuel|prior|transition|reversal|history|last_two",covariate,ignore.case=TRUE)],na.rm=TRUE),.groups="drop")
write.csv(cd,file.path(od,"landmark_calibration_diagnostics.csv"),row.names=FALSE);write.csv(b,file.path(td,"Table_landmark_balance_calibrated_IPCW.csv"),row.names=FALSE);write.csv(bs,file.path(od,"landmark_calibrated_balance_summary.csv"),row.names=FALSE);write.csv(e,file.path(od,"landmark_calibrated_weight_ESS.csv"),row.names=FALSE);write.csv(wd,file.path(od,"landmark_calibrated_weight_diagnostics.csv"),row.names=FALSE)
stability_review<-all(wd$maximum<10)&all(wd$top1_share<.15)
pass<-all(cd$converged)&all(bs$max_abs_SMD<.10)&all(bs$fuel_history_max<.10)&all(e$ESS[e$scope=="treatment-specific"]>=100)&stability_review
gate<-data.frame(label=ifelse(pass,"LANDMARK CALIBRATED FINAL WEIGHT GATE PASSED","LANDMARK CALIBRATED FINAL WEIGHT GATE FAILED"),required_imputations="5/5",calibration_pass=all(cd$converged),balance_pass=all(bs$max_abs_SMD<.10),fuel_history_pass=all(bs$fuel_history_max<.10),ESS_pass=all(e$ESS[e$scope=="treatment-specific"]>=100),stability_review_pass=stability_review,top1_share_range=paste0(round(min(wd$top1_share),4),"-",round(max(wd$top1_share),4)),maximum_weight=max(wd$maximum),maximum_SMD=max(bs$max_abs_SMD),minimum_treatment_ESS=min(e$ESS[e$scope=="treatment-specific"]));write.csv(gate,file.path(od,"landmark_calibrated_final_gate.csv"),row.names=FALSE);writeLines(c(gate$label,paste(names(gate),gate,collapse="; ")),file.path(ld,"06b_landmark_calibrated_IPCW.log"),useBytes=TRUE);print(bs);print(e);print(gate)
