options(stringsAsFactors=FALSE,warn=1)
suppressPackageStartupMessages({library(dplyr);library(survey)})
set.seed(20260815)
project<-normalizePath(getwd(),winslash="/",mustWork=TRUE);dd<-file.path(project,"data","causal_landmark");od<-file.path(project,"results","causal_landmark");td<-file.path(project,"tables","causal_landmark");ld<-file.path(project,"logs","causal_landmark")
fg<-read.csv(file.path(od,"landmark_final_weight_gate.csv"));if(fg$label!="LANDMARK FINAL WEIGHT GATE PASSED"){out<-data.frame(outcome=c("HD_z","KDM_BAA"),estimate=NA_real_,lower95=NA_real_,upper95=NA_real_,p_value=NA_real_,status="WITHHELD",reason=paste0("Final treatment+IPCW gate failed: maximum SMD=",round(fg$maximum_SMD,3)," exceeded 0.10."));write.csv(out,file.path(td,"Table_landmark_HD_KDM_effects.csv"),row.names=FALSE);writeLines(c("LANDMARK_OUTCOME=NOT_RUN","Outcome values were not read because the final gate failed."),file.path(ld,"07_landmark_outcome_HD_KDM.log"),useBytes=TRUE);cat("LANDMARK_OUTCOME_WITHHELD\n");quit(save="no",status=0)}
ws<-readRDS(file.path(dd,"landmark_final_weights_MICE5_internal_restricted.rds"))
# Outcome values are first read here, after both prespecified gates passed.
full<-readRDS(file.path(project,"data","causal","causal_long_full_internal_restricted.rds"))%>%filter(wave==2009)%>%select(Idind,HD_z,KDM_BAA)%>%distinct()
pool1<-function(q,u){m<-length(q);qb<-mean(q);W<-mean(u);B<-var(q);T<-W+(1+1/m)*B;data.frame(estimate=qb,SE=sqrt(T),lower95=qb-qnorm(.975)*sqrt(T),upper95=qb+qnorm(.975)*sqrt(T),p_value=2*pnorm(-abs(qb/sqrt(T))),within_variance=W,between_variance=B,m=m)}
allres<-list();means<-list()
for(y in c("HD_z","KDM_BAA")){q<-u<-numeric(5);for(j in 1:5){z<-ws[[j]]%>%filter(R==1)%>%left_join(full,by="Idind");des<-svydesign(ids=~commid2004,weights=~final_weight,data=z,nest=TRUE);fit<-svyglm(reformulate("A",response=y),design=des);q[j]<-coef(fit)["A"];u[j]<-vcov(fit)["A","A"];means[[length(means)+1]]<-z%>%group_by(A)%>%summarise(weighted_mean=sum(.data[[y]]*final_weight,na.rm=TRUE)/sum(final_weight[!is.na(.data[[y]])]),.groups="drop")%>%mutate(imputation=j,outcome=y)};allres[[y]]<-pool1(q,u)%>%mutate(outcome=y,contrast="clean-only 2006 versus continued any-solid 2006",estimand="ATO in 2004 any-solid overlap population",clusters="community")}
res<-bind_rows(allres)%>%select(outcome,contrast,estimand,everything());write.csv(res,file.path(td,"Table_landmark_HD_KDM_effects.csv"),row.names=FALSE);write.csv(bind_rows(means),file.path(od,"landmark_weighted_group_means.csv"),row.names=FALSE);writeLines(c("LANDMARK_OUTCOME=PASS","MICE m=5 Rubin pooling; community-clustered robust variance; marginal model outcome~A."),file.path(ld,"07_landmark_outcome_HD_KDM.log"),useBytes=TRUE);print(res)
