options(stringsAsFactors=FALSE,warn=1)
suppressPackageStartupMessages({library(dplyr);library(tidyr);library(WeightIt);library(cobalt)})
set.seed(20260815)
project<-normalizePath(getwd(),winslash="/",mustWork=TRUE);d<-readRDS(file.path(project,"data","causal","causal_long_full_internal_restricted.rds"))%>%select(-any_of(c("HD_z","KDM_BAA")));td<-file.path(project,"tables","causal_landmark");ld<-file.path(project,"logs","causal_landmark")
scan<-function(baseyr,tyr){w<-d%>%filter(wave%in%c(baseyr,tyr))%>%select(Idind,wave,fuel_state,age,sex,province,urban,education_years,income_asinh,asset_count,smoking,alcohol)%>%pivot_wider(names_from=wave,values_from=c(fuel_state,age,sex,province,urban,education_years,income_asinh,asset_count,smoking,alcohol),names_sep="_");fb<-paste0("fuel_state_",baseyr);ft<-paste0("fuel_state_",tyr);z<-w%>%filter(.data[[fb]]%in%c("solid_only","mixed"),!is.na(.data[[ft]]))%>%mutate(A=as.integer(.data[[ft]]=="clean_only"),previous_fuel=factor(.data[[fb]]),age=.data[[paste0("age_",baseyr)]],sex=factor(.data[[paste0("sex_",baseyr)]]),province=factor(.data[[paste0("province_",baseyr)]]),urban=.data[[paste0("urban_",baseyr)]],education=.data[[paste0("education_years_",baseyr)]],income=.data[[paste0("income_asinh_",baseyr)]],assets=.data[[paste0("asset_count_",baseyr)]],smoking=.data[[paste0("smoking_",baseyr)]],alcohol=.data[[paste0("alcohol_",baseyr)]])
 for(v in c("age","urban","education","income","assets","smoking","alcohol")){z[[paste0(v,"_m")]]<-as.integer(is.na(z[[v]]));med<-median(z[[v]],na.rm=TRUE);if(!is.finite(med))med<-0;z[[v]][is.na(z[[v]])]<-med}
 if(sum(z$A==1)<20)return(data.frame(treatment_landmark=tyr,eligibility_landmark=baseyr,eligible_N=nrow(z),clean_transition_N=sum(z$A==1),continued_any_solid_N=sum(z$A==0),max_abs_SMD=NA,mean_abs_SMD=NA,ESS_clean=NA,ESS_any_solid=NA,propensity_overlap="insufficient treated count",decision="FAIL"))
 f<-A~previous_fuel+age+sex+province+urban+education+income+assets+smoking+alcohol+age_m+urban_m+education_m+income_m+assets_m+smoking_m+alcohol_m;ow<-weightit(f,data=z,method="glm",estimand="ATO");bt<-bal.tab(f,data=z,weights=ow$weights,method="weighting",estimand="ATO",un=TRUE);b<-abs(bt$Balance$Diff.Adj);ec<-with(z,sum(ow$weights[A==1])^2/sum(ow$weights[A==1]^2));e0<-with(z,sum(ow$weights[A==0])^2/sum(ow$weights[A==0]^2));p<-ow$ps;ok<-max(b,na.rm=TRUE)<.10&min(ec,e0)>=100
 data.frame(treatment_landmark=tyr,eligibility_landmark=baseyr,eligible_N=nrow(z),clean_transition_N=sum(z$A==1),continued_any_solid_N=sum(z$A==0),max_abs_SMD=max(b,na.rm=TRUE),mean_abs_SMD=mean(b,na.rm=TRUE),ESS_clean=ec,ESS_any_solid=e0,propensity_overlap=paste0("range ",round(min(p),3),"-",round(max(p),3)),decision=ifelse(ok,"PASS","FAIL"))}
out<-bind_rows(scan(2000,2004),scan(1997,2000));write.csv(out,file.path(td,"Table_landmark_feasibility_scan.csv"),row.names=FALSE);writeLines("LANDMARK_FEASIBILITY_SCAN=PASS_DIAGNOSTIC_ONLY",file.path(ld,"09_landmark_feasibility_scan.log"),useBytes=TRUE);print(out)

